[package]
name = "edecl"
version = "0.1.0"
edition = "2021"

[dependencies]
copyspan = "0.1.0"
num-bigint = { version = "0.4.6", default-features = false, features = ["std"] }
num-rational = { version = "0.4.2", default-features = false, features = ["num-bigint", "num-bigint-std", "std"] }
